name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install JavaScript dependencies
        run: bun install --frozen-lockfile

      - name: Run Oxlint
        run: bun run lint

      - name: Install uv
        uses: astral-sh/setup-uv@v9

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --group dev
        working-directory: python

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage combine
          uv run coverage html --skip-covered --skip-empty
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          uv run coverage report --fail-under=35
        working-directory: python
